### ISSUE TITLE
Define Release Standard for EIC instance

### ISSUE THREAD

**Issue by sandrahoang686** [NASA-IMPACT/veda-config-eic#116]
We can better define some release standards here when deploying EIC instance. Tagging, releases, changelogs, frequency for example can be discussed and documented so some process can be created.

cc @agurvich

**Comment by agurvich** [comment]
Thanks @sandrahoang686 , do you have feedback from y'all's perspective about the current "process?" I'll be honest that from the EIC perspective the multiple checks, linked PRs, etc. for minor changes to show up on the live site is pretty cumbersome. I am not enthusiastic to add additional layers of manual boilerplate but am certainly open to discussing ways we can streamline the process with templates, scripts, GitHub actions, etc...

**Comment by aboydnw** [comment]
Meeting scheduled for Thursday, June 6

**Comment by aboydnw** [comment]
Notes
- Alex often gets a request for earth.gov that is usually minor, like a content change. He has to make a PR and get that approved. Then he has to make another PR for a version release, and often they have to pull the new veda-ui version in order for it to go through. "Because we have to release something"
- So it feels very convoluted for what is really a minor change
- And it can also release some unforeseen changes, when they have to include core veda-ui changes, by bumping the package.json version number

Need
- They need to respond quickly to urgent requests for small changes, often to content
- We need to communicate better what we are working on, and how that affects the look and feel of the instances

Some open questions:
- How can we streamline the process for the content updates so Alex doesn't have to update the version number in order to merge into main? 
- Can we document the process of merging content and, separately, updating the version number?

**Comment by sandrahoang686** [comment]
**Notes from 6/6 Mtg:**
1. When there are small content changes unrelated to veda-ui, can just one PR be opened from feature branch to main (production)? In the goal of streamlining the process to not need to go through the approval process twice (staging/develop & main/production)
2. When it comes to grabbing veda-ui changes, how can there be more communication here about when EIC should grabs these updates?

@agurvich @aboydnw Do those two questions capture what came out the end of the meeting? If not please feel free to add/adjust. I'll offer suggestions for these two though...

1. Having extra merge requirement layers are for extra insurance to make sure nothing gets merged to production (main) without it going through multiple rounds of review and testing. This is for best practices to go through develop to get to main (staging -> prod). But its really up to the owners of the code repos to decide this, I would advise to go through develop even for small content changes but that is up to you all really. If you need quicker attention on these PRs after tagging us, feel free to ping as well and that should help move things quickly if needed
2. For this case, when pulling in the latest veda-ui release changes, I think it might make sense to open up a PR from a feature branch to develop (anybody can do this here and devseeders can take the lead for the initial time being till revisited) and before it gets merged to develop we would need a hard approval from you @agurvich? This way you will still get to decide when veda-ui updates make it to develop and can go through the deploy previews and know exactly what is getting merged? We can also help you and your help desk team out here 😉. What do you think?

**Comment by agurvich** [comment]
Hi @sandrahoang686 @aboydnw , coming back to this (finally) after my trip last week and catching up on urgent asks for the physical EIC exhibit(s). I think @sandrahoang686  has articulated the questions we want to answer very well. For 1. , I tend to disagree that the develop branch is adding a layer of insurance in these cases because the extra PR from develop to main is usually generated after the PR to develop is approved after review is done. I personally never open the develop page and I don't even remember the URL.  I had to ask @slesaad for the password the one time it was relevant for a new feature: the hyperweb. 

I think for small content changes it makes sense to merge directly into main, post review on the deploy previews. This will avoid having to open a PR from the develop branch into the main branch and bumping the version number. This would require rebasing the develop branch before merging for feature additions, but that shouldn't be a problem since there typically won't be merge conflicts between content and features (and they can be identified in the develop branch before being pushed to main anyway).

**Comment by slesaad** [comment]
I'm fine with bypassing develop for small content edits, if that's makes the process easier.

Answering your question,
> For example, I find frequently that there are times after y'all approve a PR but then don't merge it. Is there a process reason for that you could better help me understand?

I think the general understanding is that the author is responsible for merging the PR, not the reviewer. That's the reason we don't merge your PRs. That also allows multiple people to review the PR before it's merged.

**Comment by sandrahoang686** [comment]
@agurvich @slesaad alright, definitely both of your calls on here! sounds fine with me if it works for you all. So if I understand correctly then, all other changes (veda-ui upgrade and changes to override components) should go through staging (develop) still? Only exceptions are small content changes to the mdx files?

**Comment by slesaad** [comment]
that's what I'm thinking!

**Comment by agurvich** [comment]
I added new labels "content-update" and "feature-update" to help us explicitly identify the two cases. Feel free to change the colors lol.
