### ISSUE TITLE
Find out how to embed YouTube video galleries

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#15]
Several EIC content pages include reels of videos (hosted on YouTube) like this:

![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/32365599-f559-4d16-a2f3-3e399541ec34)

How do we present these in the first round? To me, this feature has low priority for the first release and should consider shortcuts like

1. A playlist embed snippet from YouTube in an iframe
2. A grid / reel of cards that are external links to the YouTube videos
3. Something else simple that does not require new components

## Acceptance criteria

- [ ] Found out how to embed YouTube video galleries for first release

**Comment by j08lue** [comment]
Or putting each video on a new paragraph like here:

![image](https://github.com/NASA-IMPACT/veda-config-eic/assets/3404817/8815c7ea-6af7-4d64-8f5b-36cf6486b3ce)

**Comment by hanbyul-here** [comment]
I understand the need to effectively organize video content, but Carousel is generally not received very well by users. (Very small number of people will actually interact with it: https://erikrunyon.com/2013/07/carousel-interaction-stats/ ) It is something to consider.

**Comment by agurvich** [comment]
Point taken. Additional argument against a carousel: after talking with EGIS we're not going to get whitelisted for embedding the existing carousels. If we wanted to do it, we'd have to export the existing components (which I can do after I move them to some kind of enterprise interface) and then include the ArcGIS Javascript SDK in our package.json. Then we'd put the raw component code somewhere and render it locally instead of embedding in an iframe. 

That sounds like a nightmare IMO and if we wanted a carousel we might as well just build one ourselves. If we don't want a carousel we have to decide how to show 23 embedded youtube videos for the hyperwall page and, in general, these content collections will grow to ~10+ as more content is developed. So 23 is not really an edge case though it is probably larger than most will become. I don't love it but I don't really know what else to do... a video grid?  The carousel I put together on the current content pages _works_ it's just ugly. 

I think fleshing it out might legitimately be the path of least resistance ¯\\\_(ツ)_/¯

**Comment by j08lue** [comment]
> I don't love it but I don't really know what else to do... a video grid?

@hanbyul-here, @sandrahoang686 and I just discussed three options to consider:

1. Reviving a carousel component she had been working on earlier
2. A grid of `asLink` cards which just link to the videos on YouTube
3. Same cards but in a horizontal scroll reel we already have ("Featured stories" like).
4. I guess a fourth one would be to continue building out the component you started, @agurvich.

I'll defer to @hanbyul-here to judge how to move forward...

**Comment by agurvich** [comment]
I kind of like option #3 personally-- I think we don't lose much with the external link vs. embed (so long as it opens in a new tab). I also think it's easier to scroll through a bunch of content vs. clicking on the carousel. What do you think @hanbyul-here ?

**Comment by hanbyul-here** [comment]
I apologize that I missed the conversation from yesterday. I moved forward with the 1st option in this pr: https://github.com/NASA-IMPACT/veda-config-eic/pull/23
