### ISSUE TITLE
Create the group pages (themes, visit, teach) and put them into the top nav

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#5]
There are three top-level content groups leading users deeper into the content of the EIC: themes, features of the physical EIC for users to visit, and teaching resources.

We need to present these three groups to people.

We decided to create pages for them and reference them in the top nav, themes being the most prominent one and first item in the main nav and visit and teaching pages (pls refer to designs for exact titles) in the secondary nav.

>**Note**
Since horizontal space in the top nav might get too narrow e.g. on a tablet, we need to figure out where to put the extra secondary nav items. Earlier, we decided that all of these should go into the hamburger (actually kebab) menu that we created for that purpose. Maybe that should be our first solution - putting the visit and teach pages below that hamburger menu and if we have time, we can make a responsive solution where they are shown next to "About" on wide screens and go into the menu if space is scarce, as @faustoperez suggested?

## Acceptance criteria

- [x] Pages exist
- [x] Pages are accessible from the top navs
- [x] Pages have content

**Comment by sandrahoang686** [comment]
* Includes flushing out the `About` page as well
* Possibly 2ndary main navigation?

**Comment by j08lue** [comment]
> * Possibly 2ndary main navigation?

Yes - pls see the note I added to the issue description above. 🙏

**Comment by hanbyul-here** [comment]
I moved forward with the current solution (extra pages in hamberger menu)
![Screen Shot 2023-11-10 at 2 31 43 PM](https://github.com/NASA-IMPACT/veda-config-eic/assets/4583806/ce259ba8-4ded-4f7d-ad46-e069c3aeebde)

**Comment by agurvich** [comment]
I would definitely like to explore the responsive solution, though I know we don't really have a lot of time. Putting the Visit and Teach into the 3 dots menu makes them hard to find. I also think we should consider replacing the 3 dots with a hamburger for all screen sizes since they function (almost) the same and 3 dots is usually associated with customization/options in this context. Or maybe putting the word "More" could invite people to click it? I'm just afraid no one will find the pages  as it is now :\

**Comment by j08lue** [comment]
I'll close this ticket as completed and defer to a follow-up discussion to revisit the nav question.
