### ISSUE TITLE
Hide the `/stories` hub

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#6]
We want to use `stories` for all content that should get featured on an EIC page (themes, visit, teach), except for datasets of course. See rationale in the upstream ticket.

Users should discover this content through the groupings that the EIC intends, rather than dynamically through a (filterable / searchable) master catalog, since these pieces may require the lineage / context of the main feature or grouping to make sense to users.

Therefore, the idea is to hide the master `/stories` hub. Instead, there will be the three pages via which users can find relevant items.

## Acceptance criteria

- [ ] Users do not stumble over a master catalog where stories that assume context are shown side by side, which would be confusing.

**Comment by hanbyul-here** [comment]
👋 I just realized that some items that I considered as a detail of implementation, seem to be actually the core of the problem. So I will write down what I am thinking now. 

VEDA UI currently offers many ways of overriding existing things, but not many ways to disable/hijack the routes. Rather than trying to make one-off thing (such as disabling the hub and hooking a story link to a nav item) for EIC, I am wondering if we can do the following.

1. There will be a landing page for `/stories`, `/teach`, `/learn`. Each page will be an mdx component in config instance, but not a story. Such as : https://github.com/NASA-IMPACT/veda-config-eic/pull/11/files (How it looks: https://deploy-preview-9--earth-information-center.netlify.app/stories) 
2. But everything linked from `/stories`, `/teach`, `/learn` will be a story. 
3. If any of those landing pages`/stories`, `/teach`, `/learn` should be linked as a card form, this should be handled as https://github.com/NASA-IMPACT/veda-ui/issues/728 
4. To make general development easier, we can have an attribute such as `type: theme` only for eic instance. (veda ui doesn't need to know about the attributes.) So each page can be populated in somewhat programmatic way (ex. https://github.com/NASA-IMPACT/veda-config-eic/pull/9/files#diff-382dacc7f9a8965c056493178bd4470aa1367edd7f965467d36b36a4b3454cb4R25) 

I know you @j08lue already communicated your idea of everythiing being a story with other stakeholders and checked in with me about the plan. I apologize that I did not express my idea earlier.  Also, I am unsure if there is any potential problem with the approach I am thinking, so lmk if you can see any problem, I can revisit my thoughts 🙇

**Comment by j08lue** [comment]
Great write-up, @hanbyul-here. I think this is pretty much what I was thinking of, actually. 😬 

## Routes

> but not many ways to disable/hijack the routes

I agree - we should not do that for now. We can just omit the top nav entry for `/stories` but it could continue to exist in its current form.


## Programmatic item assignment?

> So each page can be populated in somewhat programmatic way

To me, this programmatic page population could come after the Nov 17th release. Until then, manual selection of the items to feature on these pages would be totally fine, if that is faster / easier.

Please remember that themes are nested:

```
themes overview (page /themes)
└── theme A (story? /stories/theme-a-intro)
    ├── theme A feature 1 (story /stories/theme-a-feature-1)
    └── theme A feature 2 (story/link https://example.com)
```

I think that could complicate programmatic assignment (push / tag-filter-based).

**Comment by hanbyul-here** [comment]
Okay, I can see that the introduction of tags can complicate things. I will move forward with some manual curation (probably an array of story ids) to select 'stories'.

I'd like a clarification on 

> We should omit the top nav entry for /stories but it could continue to exist in its current for

What does this mean? Does this mean 'Theme' item should not exist on the nav? or just leave as currently it is?

**Comment by j08lue** [comment]
> Does this mean 'Themes' item should not exist on the nav?

"Themes" should be in the nav, but it could link to a custom page listing themes features, similar to the Visit and Teach pages, I guess.

My goal here would be to keep `/stories` intact, reduce the overrides, and solve the special needs for these context-specific entrypoints (themes, visit, teach) differently for now.

**Comment by hanbyul-here** [comment]
The suggested approach above uses a custom component (by overriding the existing hub), but the page would not have the custom route. (it will be linked to `/stories`) 

I need clarification on what is suggested for development convenience vs. requirement. What is required behavior?

**Comment by j08lue** [comment]
Requirements:

1. "Themes" main nav item -> page featuring the 9 theme intro stories

Development convenience:

1. `/stories` stays intact
2. Nav gets customizable + we just omit a nav item for `/stories`

Just for the record...
