### ISSUE TITLE
Turn GHG theme card into link to GHG Center

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-config-eic#76]
Currently, the theme card for Greenhouse Gases on the Themes page links to a separate page with intro to GHG and a link to a The NASA Carbon Monitoring System. https://earth.gov/stories/greenhouse_gases

We would like to make users looking for information about greenhouse gases aware of the GHG Center - either instead of other resources or at least most prominently.

Two possible ways were discussed:

1. Make the GHG Center very apparent on the GHG theme pagehttps://earth.gov/stories/greenhouse_gases (e.g. by having the same banner there as on the home page)
2. Remove the EIC GHG theme page and instead send users directly to the GHG Center

The second one was preferred when discussed in the GHG Center dev meeting (30 Nov) but the first one is perhaps also an option, if there are strong reasons for it.

Deadline: by Monday 4 Dec start of day - i.e. effectively by Friday 1 Dec EOB.

## Acceptance criteria

- [ ] Users looking for GHG information find the GHG Center everywhere GHG is mentioned on EIC

**Comment by faustoperez** [comment]
Hi! Since this is an urgent task, our preferred approach would be option 1, as option 2 would have implications on the site navigation as it introduces an exception in the content hierarchy, which might translate into a not-so-clear user experience.

We have prepared a mockup of the theme page with the GHG banner at the top.
Link to Figma file here 👉 https://www.figma.com/file/2Vd0SDhFOTBJaYioJPr0Ei/Earth.gov?type=design&node-id=732%3A6276&mode=design&t=r9lccFKWTXSsetlD-1

<img width="1440" alt="Individual theme - Greenhouse Gases" src="https://github.com/NASA-IMPACT/veda-config-eic/assets/12268629/da1c0e6f-9b75-4fdd-9220-6469ad7fef52">

**Comment by deborahUAH** [comment]
this is a good immediate solution in my opinion. THanks!

**Comment by agurvich** [comment]
I agree with @deborahUAH, I think this is good. I also think that this approach scales without loss of content for future centers. For example, consider the scenario where we actually have GHG stories that are written to a public audience. How would users access them if we remove the GHG theme page? They would have to live in the GHG Center's stories, mixed in with the stories geared for a more technical audience. As we add additional centers we'd have to migrate existing stories from their earth.gov homes to earth.gov/agriculturecenter (for example)-- and then mix them in with the more technical stories. 

I understand the preference for option 2 expressed in the GHG Center dev meeting but this seems like a good compromise and on brand with the "Want to learn more? Visit GHG Center" approach.
